pweb_accueil:
    resource: "@PwebAccueilBundle/Resources/config/routing.yml"
    prefix:   /

pweb_compte:
    resource: "@PwebCompteBundle/Resources/config/routing.yml"
    prefix:   /

pweb_user:
    resource: "@PwebUserBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
