<?php

namespace Pweb\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcheteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcheteurRepository extends EntityRepository
{
}
