<?php

namespace Pweb\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProdRepository extends EntityRepository
{
}
