<?php

namespace Pweb\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutComRepository extends EntityRepository
{
}
