pweb_accueil:
    pattern:  /Accueil
    defaults: { _controller: PwebAccueilBundle:Accueil:index }

pweb_produits:
    pattern:  /Produits
    defaults: { _controller: PwebAccueilBundle:Produits:index }
