pweb_accueil:
    pattern:  /Accueil
    defaults: { _controller: PwebAccueilBundle:Accueil:index }

pweb_patch:
    pattern:  /
    defaults: { _controller: PwebAccueilBundle:Accueil:index }

pweb_produits:
    pattern:  /Produits
    defaults: { _controller: PwebAccueilBundle:Produits:index }

info_produits:
    pattern: /Produits/info_produits/{idProd}
    defaults: { _controller: PwebAccueilBundle:Produits:showInfo }

