parameters:
#    pweb_accueil.example.class: Pweb\AccueilBundle\Example

services:
#    pweb_accueil.example:
#        class: %pweb_accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
