login:
    pattern:  /login
    defaults: { _controller: PwebUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

inscription:
    pattern: /inscription
    defaults: { _controller: PwebUserBundle:Security:inscription }