parameters:
#    pweb_user.example.class: Pweb\UserBundle\Example

services:
#    pweb_user.example:
#        class: %pweb_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
